export const APPLICATION_TYPE = {
  CANCELLATION_APPLICATION: 1,
  SUSPEND_APPLICATION: 2,
  COACH_CHANGE_APPLICATION: 3,
} as const

export type APPLICATION_TYPE = (typeof APPLICATION_TYPE)[keyof typeof APPLICATION_TYPE]
